BookWings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from .views import index, about

from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', index, name='home'),
    path('home/', index, name='home'),
    path('about/', about, name='about'),
    path('', include('accounts.urls')),
    path('books/', include('books.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('delivery/', include('delivery.urls')),
    # your other paths here
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT})
]

cart/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    # path('add-book/', addBook, name='addbook'),
    path('', view_cart, name='view_cart'),
    path('add-to-cart/', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/', remove_from_cart, name='remove_from_cart'),
    path('update-quantity/', update_quantity, name='update_quantity'),
    path('get-cart-size/', get_cart_size, name='get_cart_size'),
]

Account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class UserManager(BaseUserManager):
    def create_user(self, phone_number, email, first_name, last_name, password=None):
        if not phone_number:
            raise ValueError('Users must have a phone number')

        user = self.model(
            phone_number=phone_number,
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, phone_number, email, password):
        user = self.create_user(phone_number, email, password)
        user.is_admin = True
        user.save(using=self._db)
        return user


# Create your models here.
class User(AbstractBaseUser):
    first_name = models.CharField(max_length=20, blank=True)
    last_name = models.CharField(max_length=40, blank=True)

    phone_number = models.CharField(max_length=20, blank=False, unique=True)
    email = models.EmailField(max_length=255, blank=False, unique=True)
    gender = models.BooleanField(default=True)

    date_joined = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'email']

    objects = UserManager()

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=255)

    def __str__(self):
        return self.address

templates/home/about.html
{% extends 'layouts/base.html' %}
{% block title %}
About Us
{% endblock %}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Về chúng tôi</h1>
        </div>
    </div>
</header>

<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row">
            <div class="col-lg-6">
            <h2 class="fw-bolder">Chúng tôi là ai?</h2>
            <p class="lead">BookWings là một hệ thống bán sách trực tuyến hàng đầu tại Việt Nam. Chúng tôi cung cấp một nền tảng mua bán sách trực tuyến, giúp người dùng dễ dàng tìm kiếm và mua sách một cách nhanh chóng và thuận tiện.</p>
            </div>
            <div class="col-lg-6">
            <h2 class="fw-bolder">Sứ mệnh của chúng tôi</h2>
            <p class="lead">Sứ mệnh của BookWings là mang đến cho người dùng trải nghiệm mua sắm sách trực tuyến tốt nhất, giúp họ dễ dàng tìm kiếm và mua sách một cách nhanh chóng và thuận tiện.</p>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6">
            <h2 class="fw-bolder">Giá trị của chúng tôi</h2>
            <p class="lead">Chúng tôi cam kết cung cấp cho khách hàng những cuốn sách chất lượng cao, đa dạng về thể loại và nguồn gốc. Chúng tôi luôn đảm bảo rằng sách được bán trên nền tảng của chúng tôi đáp ứng được các tiêu chuẩn chất lượng và đáng tin cậy.</p>
            </div>
            <div class="col-lg-6">
            <h2 class="fw-bolder">Đội ngũ của chúng tôi</h2>
            <p class="lead">Chúng tôi có một đội ngũ chuyên gia đam mê sách và công nghệ, luôn sẵn sàng hỗ trợ và tư vấn cho khách hàng. Đội ngũ của chúng tôi luôn nỗ lực để mang đến cho khách hàng trải nghiệm mua sắm sách tốt nhất.</p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/home/index.html
{% extends 'layouts/base.html' %}
{% block title %}
    BookWings - Hệ thống bán sách hàng đầu Việt Nam
{% endblock %}

{% block content %}
    <!-- Header-->
    <header class="bg-dark py-5 rounded-2">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Welcome to BookWings</h1>
                <p class="lead fw-normal text-white-50 mb-0">Explore our vast collection of books and find your next
                    favorite read.</p>
            </div>
        </div>
    </header>
    <!-- Section-->
    <section class="py-5" style="background-color: #d7d8da">
        <div class="container px-4 px-lg-5 mt-5 bg-white rounded-4 shadow">
            <br>
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h2 class="display-6 text-uppercase fw-bold mb-0 text-danger">Trendy Books <svg xmlns="http://www.w3.org/2000/svg" width="1.35em" height="1.2em" viewBox="0 0 576 512"><path fill="#ea0606" d="M384 160c-17.7 0-32-14.3-32-32s14.3-32 32-32h160c17.7 0 32 14.3 32 32v160c0 17.7-14.3 32-32 32s-32-14.3-32-32v-82.7L342.6 374.6c-12.5 12.5-32.8 12.5-45.3 0L192 269.3L54.6 406.6c-12.5 12.5-32.8 12.5-45.3 0s-12.5-32.8 0-45.3l160-160c12.5-12.5 32.8-12.5 45.3 0L320 306.7L466.7 160z"/></svg></h2>
                <a class="btn btn-outline-dark" href="{% url 'view_books' %}">More<i
                        class="bi bi-arrow-right-short"></i></a>
            </div>
            {% include "books/book_render.html" with books=books is_trending=True %}
        </div>
        <div class="container px-4 px-lg-5 mt-5 bg-white rounded-4 shadow">
            <br>
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h2 class="display-6 text-uppercase fw-bold mb-0 text-danger">Hot coupons! <i class="bi bi-fire h2"></i></h2>
                {% if user.is_authenticated %}
                    <a class="btn btn-outline-dark" href="{% url 'view_books' %}">Use now<i
                            class="bi bi-arrow-right-short"></i></a>
                {% endif %}
            </div>
            {% include "coupons/coupons.html" with coupons=coupons %}
        </div>
    </section>
{% endblock %}

templates/home/login.html
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginModalLabel">Login</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div id="login_error"></div>
                <form name="login_form" id="login_form" method="post" action="{% url 'login' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_username">Phone number or Email</label>
                        <input required type="text" id="txtUsername" name="username" value="{{ username }}" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="id_password">Password</label>
                        <input required type="password" id="txtPassword" name="password" class="form-control">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-dark" id="login">Login</button>
            </div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function() {
        $('#login').click(function() {
            if ($('#txtUsername').val() == '' || $('#txtPassword').val() == '') {
                $('#login_error').html("Please fill in all fields");
                $('#login_error').addClass('alert alert-danger');
            } else {

                $.ajaxSetup({
                    headers: { "X-CSRFToken": "{{ csrf_token }}" }
                });

                $.ajax({
                    type: 'POST',
                    url: "{% url 'login' %}",
                    data: {
                        'username': $('#txtUsername').val(),
                        'password': $('#txtPassword').val()
                    },
                    success: function(data) {
                        if (data.status == 'success') {
                            window.location.href = "{% url 'home' %}";
                        } else {
                            $('#login_error').html(data.message);
                            $('#login_error').addClass('alert alert-danger');
                        }
                    },

                    error: function(request, status, error) {
                        $('#login_error').html("Error: " + error);
                        $('#login_error').addClass('alert alert-danger');
                    }
                });
            }
        });
    });
</script>

templates/home/register.html
<div class="modal fade" id="registerModal" tabindex="-1" aria-labelledby="registerModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="registerModalLabel">Register</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="register-model">
                {% comment %} <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_phone_number">Phone Number</label>
                        {{ form.phone_number }}
                    </div>
                    <div class="form-group">
                        <label for="id_email">Email</label>
                        {{ form.email }}
                    </div>
                    <div class="form-group">
                        <label for="id_password">Password</label>
                        {{ form.password }}
                    </div>
                    <div class="form-group">
                        <label for="id_first_name">First Name</label>
                        {{ form.first_name }}
                    </div>
                    <div class="form-group">
                        <label for="id_last_name">Last Name</label>
                        {{ form.last_name }}
                    </div>
                    <button type="submit" class="btn btn-primary">Register</button>
                </form> {% endcomment %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="register-btn">Register</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        // load register page
        $("#register-model").load("{% url 'register' %}", function() {
            $("#register-model input").addClass("form-control");
            $("#register-model label").addClass("form-label");
        });

        

        $("#register-btn").click(function() {
            var form = $("#register-form").serialize();
            
            if ($("#id_phone_number").val() == '' || $("#id_email").val() == '' || $("#id_password").val() == '' || $("#id_first_name").val() == '' || $("#id_last_name").val() == '') {
                $("#register-error").html("Please fill in all fields");
                $("#register-error").addClass("alert alert-danger");
                return;
            }

            $.post("{% url 'register' %}", form, function(data) {
                if (data.status == 'success') {
                    $("#register-error").html(data.message);
                    $("#register-error").removeClass("alert alert-danger");
                    $("#register-error").addClass("alert alert-success");
                    setTimeout(function() {
                        $("#registerModal").modal('hide');
                        $("#register-error").html("");
                        $("#register-error").removeClass("alert alert-success");
                        // =========================
                        var id_phone_number = $("#id_phone_number").val();
                        var password = $("#id_password").val();
                        // =========================

                        $("#register-form").trigger("reset");
                        $("#login-form").trigger("reset");
                        $("#login-error").html("");
                        $("#login-error").removeClass("alert alert-danger");
                        $("#loginModal").modal("show");
                        // find login_form and fill in the values
                        $("#txtUsername").val(id_phone_number);
                        $("#txtPassword").val(password);
                    }, 1000);

                } else {
                    var errors = data.errors;
                    // convert this to json
                    errors = JSON.parse(errors);
                    key = Object.keys(errors)[0]
                    var error = errors[key];
                    if (error[0].message == "This field is required.") {
                        $("#register-error").html(key + " " + error[0].message);
                    } else {
                        $("#register-error").html(error[0].message);
                    }
                    $("#register-error").addClass("alert alert-danger");
                }
            });
        });
    });
</script>