BookWings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from .views import index, about

from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', index, name='home'),
    path('home/', index, name='home'),
    path('about/', about, name='about'),
    path('', include('accounts.urls')),
    path('books/', include('books.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('delivery/', include('delivery.urls')),
    # your other paths here
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT})
]

cart/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    # path('add-book/', addBook, name='addbook'),
    path('', view_cart, name='view_cart'),
    path('add-to-cart/', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/', remove_from_cart, name='remove_from_cart'),
    path('update-quantity/', update_quantity, name='update_quantity'),
    path('get-cart-size/', get_cart_size, name='get_cart_size'),
]

Account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class UserManager(BaseUserManager):
    def create_user(self, phone_number, email, first_name, last_name, password=None):
        if not phone_number:
            raise ValueError('Users must have a phone number')

        user = self.model(
            phone_number=phone_number,
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, phone_number, email, password):
        user = self.create_user(phone_number, email, password)
        user.is_admin = True
        user.save(using=self._db)
        return user


# Create your models here.
class User(AbstractBaseUser):
    first_name = models.CharField(max_length=20, blank=True)
    last_name = models.CharField(max_length=40, blank=True)

    phone_number = models.CharField(max_length=20, blank=False, unique=True)
    email = models.EmailField(max_length=255, blank=False, unique=True)
    gender = models.BooleanField(default=True)

    date_joined = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'email']

    objects = UserManager()

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=255)

    def __str__(self):
        return self.address

templates/user/admin-profile.html
{% extends 'layouts/base.html' %}

{% block title %}Personal Information{% endblock %}

{% block content %}
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Admin {{ user.first_name }}'s Information</h1>
            </div>
        </div>
    </header>
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row">
                <div class="col-6">
                    <label class="sr-only mb-0 mx-2" for="id_phone">Phone number:</label>
                    <input type="text" value="{{ user.phone_number }}" class="form-control mb-2" id="id_phone" disabled>
                    <label class="sr-only mb-0 mx-2" for="id_email">Email:</label>
                    <input type="text" value="{{ user.email }}" class="form-control mb-2" readonly id="id_email">
                    <label class="sr-only mb-0 mx-2" for="id_fname">First name:</label>
                    <input type="text" value="{{ user.first_name }}" class="form-control mb-2" id="id_fname" readonly>
                    <label class="sr-only mb-0 mx-2" for="id_lname">Last name:</label>
                    <input type="text" value="{{ user.last_name }}" class="form-control mb-2" id="id_lname" readonly>
                    <label class="sr-only mb-0 mx-2" for="id_role">Role:</label>
                    <input type="text" value="{{ user.role }}" class="form-control mb-2" id="id_role" disabled>
                </div>
                <div class="col-6">
                    <p>Avatar:</p>
                    <img src="/media/account/avatar-default.svg" alt="Avatar" class="img-fluid"
                         style="width: 200px; height: 200px;">
                    <br><br>
                    <label class="sr-only mb-0 mx-2" for="id_role">Joined Date:</label>
                    <input type="text" value="{{ user.date_joined }}" class="form-control mb-2" disabled>
                    <label class="sr-only mb-0 mx-2" for="id_role">Last Login:</label>
                    <input type="text" value="{{ user.last_login }}" class="form-control mb-2" disabled>
                    <br>
                    <a href="/accounts/profile/edit" class="btn btn-primary">Save</a>
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                            data-bs-target="#changePasswordModal">Change Password
                    </button>
                </div>
            </div>
        </div>
    </section>

    <!-- Change Password Modal -->
    <div class="modal fade" id="changePasswordModal" tabindex="-1"
         aria-labelledby="changePasswordModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="changePasswordModalLabel">Change Password</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <!-- Add your change password form here -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close
                    </button>
                    <button type="button" class="btn btn-dark" id="change-pwd">Change Password</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            $('#changePasswordModal').on('show.bs.modal', function (event) {
                const modal = $(this);
                modal.find('.modal-body').load("{% url 'change-password' %}", function () {
                    $("#change-pwd-form input").each(function () {
                        $(this).addClass('form-control');
                    });
                });

                $('#change-pwd').click(function () {
                    $.ajaxSetup({
                        headers: {"X-CSRFToken": "{{ csrf_token }}"}
                    });

                    $.ajax({
                        type: 'POST',
                        url: "{% url 'change-password' %}",
                        data: $('#change-pwd-form').serialize(),
                        success: function (response) {
                            if (response['status'] == 'success') {
                                $("#changepwd-status").html('<div class="alert alert-success" role="alert">Password changed successfully</div>');
                                setTimeout(function () {
                                    $('#changePasswordModal').modal('hide');
                                }, 1000);
                            } else {
                                $("#changepwd-status").html('<div class="alert alert-danger" role="alert">' + response['error_message'] + '</div>');
                            }
                        },
                        error: function (responseText, status, error) {
                            $("#changepwd-status").html('<div class="alert alert-danger" role="alert">' + error + '</div>');
                        }
                    });
                });
            });
        });
    </script>
{% endblock %}

templates/user/customer-profile.html
{% extends 'layouts/base.html' %}

{% block title %}Personal Information{% endblock %}

{% block content %}
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">{{ user.first_name }}'s Information</h1>
            </div>
        </div>
    </header>
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <form method="POST" action="{% url 'update-profile' %}">
                {% csrf_token %}
                <div class="row">
                    <div class="col-6">
                        <label class="sr-only mb-0 mx-2" for="id_phone">Phone number:</label>
                        <input type="text" value="{{ user.phone_number }}" class="form-control mb-2" id="id_phone"
                               disabled>
                        <label class="sr-only mb-0 mx-2" for="id_email">Email:</label>
                        <input type="text" value="{{ user.email }}" name="email" class="form-control mb-2" id="id_email">
                        <label class="sr-only mb-0 mx-2" for="id_fname">First name:</label>
                        <input type="text" value="{{ user.first_name }}" name="first_name" class="form-control mb-2" id="id_fname">
                        <label class="sr-only mb-0 mx-2" for="id_lname">Last name:</label>
                        <input type="text" value="{{ user.last_name }}" name="last_name" class="form-control mb-2" id="id_lname">
                        <label class="sr-only mb-0 mx-2" for="id_role">Role:</label>
                        <input type="text" value="{{ user.role }}" class="form-control mb-2" id="id_role" disabled>
                        <label class="sr-only mb-0 mx-2" for="id_rank">Rank:</label>
                        <input type="text" value="{{ user.get_rank_display }}" class="form-control mb-2" id="id_rank"
                               disabled>
                    </div>
                    <div class="col-6">
                        <p>Avatar:</p>
                        <img src="/media/account/avatar-default.svg" alt="Avatar" class="img-fluid"
                             style="width: 200px; height: 200px;">
                        <br><br>
                        <label class="sr-only mb-0 mx-2" for="id_role">Joined Date:</label>
                        <input type="text" value="{{ user.date_joined }}" class="form-control mb-2" disabled>
                        <label class="sr-only mb-0 mx-2" for="id_role">Last Login:</label>
                        <input type="text" value="{{ user.last_login }}" class="form-control mb-2" disabled>
                        <br>
                        <button type="submit" class="btn btn-primary">Save</button>
                        <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                                data-bs-target="#changePasswordModal">Change Password
                        </button>
                    </div>
                </div>
            </form>
            <hr>

            <div class="row">
                <div class="col-12">
                    <h2 class="fw-bolder">Address Book</h2>
                    <button type="button" class="btn mb-3" data-bs-toggle="modal"
                            data-bs-target="#addAddressModal">
                        <i class="bi bi-plus-circle"></i>&nbsp; Add New Address
                    </button>
                    <div class="list-group">
                        {% for address in addresses %}
                            <div class="list-group-item d-flex justify-content-between align-items-center">
                                {{ address }}
                                <form method="post" action="{% url 'remove-address' address.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn"><i class="bi bi-dash-circle"
                                                                         style="color: red"></i></button>
                                </form>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Change Password Modal -->
    <div class="modal fade" id="changePasswordModal" tabindex="-1"
         aria-labelledby="changePasswordModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="changePasswordModalLabel">Change Password</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <!-- Add your change password form here -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close
                    </button>
                    <button type="button" class="btn btn-dark" id="change-pwd">Change Password</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="addAddressModal" tabindex="-1" aria-labelledby="addAddressModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addAddressModalLabel">Add New Address</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" action="{% url 'update-address' %}">
                    <div class="modal-body">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_address" class="form-label">No. and Street</label>
                            <input type="text" name="local_addr" class="form-control mb-2" id="id_address" required>
                            <label for="id_commune" class="form-label">Commune</label>
                            <input type="text" name="commune" class="form-control mb-2" id="id_commune" required>
                            <label for="id_district" class="form-label">District</label>
                            <input type="text" name="district" class="form-control mb-2" id="id_district" required>
                            <label for="id_province" class="form-label">Province</label>
                            <input type="text" name="province" class="form-control mb-2" id="id_province" required>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-dark" id="id_add_addr">Add Address</button>
                    </div>
                </form>

            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {

            $('#changePasswordModal').on('show.bs.modal', function (event) {
                var modal = $(this);
                modal.find('.modal-body').load("{% url 'change-password' %}", function () {
                    $("#change-pwd-form input").each(function () {
                        $(this).addClass('form-control');
                    });
                });

                $('#change-pwd').click(function () {
                    $.ajaxSetup({
                        headers: {"X-CSRFToken": "{{ csrf_token }}"}
                    });

                    $.ajax({
                        type: 'POST',
                        url: "{% url 'change-password' %}",
                        data: $('#change-pwd-form').serialize(),
                        success: function (response) {
                            if (response['status'] == 'success') {
                                $("#changepwd-status").html('<div class="alert alert-success" role="alert">Password changed successfully</div>');
                                setTimeout(function () {
                                    $('#changePasswordModal').modal('hide');
                                }, 1000);
                            } else {
                                $("#changepwd-status").html('<div class="alert alert-danger" role="alert">' + response['error_message'] + '</div>');
                            }
                        },
                        error: function (responseText, status, error) {
                            $("#changepwd-status").html('<div class="alert alert-danger" role="alert">' + error + '</div>');
                        }
                    });
                });
            });
        });
    </script>
{% endblock %}

templates/user/view-profile.html
{% extends 'layouts/base.html' %}

{% block title %}Personal Information{% endblock %}

{% block content %}
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Personal Information</h1>
            </div>
        </div>
    </header>
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row">
                <div class="col-6">
                    <label class="sr-only mb-0 mx-2" for="id_phone">Phone number:</label>
                    <input type="text" value="{{ user.phone_number }}" class="form-control mb-2" id="id_phone" disabled>
                    <label class="sr-only mb-0 mx-2" for="id_email">Email:</label>
                    <input type="text" value="{{ user.email }}" class="form-control mb-2" readonly id="id_email">
                    <label class="sr-only mb-0 mx-2" for="id_fname">First name:</label>
                    <input type="text" value="{{ user.first_name }}" class="form-control mb-2" id="id_fname" readonly>
                    <label class="sr-only mb-0 mx-2" for="id_lname">Last name:</label>
                    <input type="text" value="{{ user.last_name }}" class="form-control mb-2" id="id_lname" readonly>
                    <label class="sr-only mb-0 mx-2" for="id_role">Role:</label>
                    <input type="text" value="{{ user.role }}" class="form-control mb-2" id="id_role" disabled>
                </div>
                <div class="col-6">
                    <p>Avatar:</p>
                    <img src="/media/account/avatar-default.svg" alt="Avatar" class="img-fluid"
                         style="width: 200px; height: 200px;">
                    <br><br>
                    <label class="sr-only mb-0 mx-2" for="id_role">Joined Date:</label>
                    <input type="text" value="{{ user.date_joined }}" class="form-control mb-2" disabled>
                    <label class="sr-only mb-0 mx-2" for="id_role">Last Login:</label>
                    <input type="text" value="{{ user.last_login }}" class="form-control mb-2" disabled>
                    <br>
                    <a href="/accounts/profile/edit" class="btn btn-primary">Save</a>
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                            data-bs-target="#changePasswordModal">Change Password
                    </button>
                </div>
            </div>

            <hr>

            <div class="row">
                <div class="col-12">
                    <h2 class="fw-bolder">Address Book</h2>
                    <button type="button" class="btn mb-3" data-bs-toggle="modal"
                            data-bs-target="#addAddressModal">
                        <i class="bi bi-plus-circle"></i>&nbsp; Add New Address
                    </button>
                    <div class="list-group">
                        {% for address in addresses %}
                            <div class="list-group-item d-flex justify-content-between align-items-center">
                                {{ address }}
                                <form method="post" action="{% url 'remove-address' address.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn"><i class="bi bi-dash-circle" style="color: red"></i></button>
                                </form>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Change Password Modal -->
    <div class="modal fade" id="changePasswordModal" tabindex="-1"
         aria-labelledby="changePasswordModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="changePasswordModalLabel">Change Password</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <!-- Add your change password form here -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close
                    </button>
                    <button type="button" class="btn btn-dark" id="change-pwd">Change Password</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="addAddressModal" tabindex="-1" aria-labelledby="addAddressModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addAddressModalLabel">Add New Address</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post" action="{% url 'update-address' %}">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_address" class="form-label">No. and Street</label>
                            <input type="text" name="local_addr" class="form-control mb-2" id="id_address" required>
                            <label for="id_commune" class="form-label">Commune</label>
                            <input type="text" name="commune" class="form-control mb-2" id="id_commune" required>
                            <label for="id_district" class="form-label">District</label>
                            <input type="text" name="district" class="form-control mb-2" id="id_district" required>
                            <label for="id_province" class="form-label">Province</label>
                            <input type="text" name="province" class="form-control mb-2" id="id_province" required>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-dark" id="id_add_addr">Add Address</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {

            $('#id_add_addr').click(function () {
                $.ajaxSetup({
                    headers: {"X-CSRFToken": "{{ csrf_token }}"}
                });

                $.ajax({
                    type: 'POST',
                    url: "{% url 'update-address' %}",
                    data: $('#addAddressModal form').serialize(),
                    success: function (response) {
                        if (response['status'] == 'success') {
                            $("#addAddressModal").modal('hide');
                            location.reload();
                        } else {
                            $("#addAddressModal").html('<div class="alert alert-danger" role="alert">' + response['error_message'] + '</div>');
                        }
                    },
                    error: function (responseText, status, error) {
                        $("#addAddressModal").html('<div class="alert alert-danger" role="alert">' + error + '</div>');
                    }
                });
            });

            $('#changePasswordModal').on('show.bs.modal', function (event) {
                var modal = $(this);
                modal.find('.modal-body').load("{% url 'change-password' %}", function () {
                    $("#change-pwd-form input").each(function () {
                        $(this).addClass('form-control');
                    });
                });

                $('#change-pwd').click(function () {
                    $.ajaxSetup({
                        headers: {"X-CSRFToken": "{{ csrf_token }}"}
                    });

                    $.ajax({
                        type: 'POST',
                        url: "{% url 'change-password' %}",
                        data: $('#change-pwd-form').serialize(),
                        success: function (response) {
                            if (response['status'] == 'success') {
                                $("#changepwd-status").html('<div class="alert alert-success" role="alert">Password changed successfully</div>');
                                setTimeout(function () {
                                    $('#changePasswordModal').modal('hide');
                                }, 1000);
                            } else {
                                $("#changepwd-status").html('<div class="alert alert-danger" role="alert">' + response['error_message'] + '</div>');
                            }
                        },
                        error: function (responseText, status, error) {
                            $("#changepwd-status").html('<div class="alert alert-danger" role="alert">' + error + '</div>');
                        }
                    });
                });
            });
        });
    </script>
{% endblock %}